-- -- LSP configuration: native `vim.lsp`
--
-- vim.diagnostic.config { virtual_text = true }
--
-- -- Default capabilities applied to all servers. `vim.lsp.config["*"]`
-- -- merges into every enabled config (see :h vim.lsp.config).
-- vim.lsp.config['*'] = {
-- }
--
-- -- rust-analyzer
-- vim.lsp.config.rust_analyzer = {
--   cargo = {
--     allFeatures = true,
--     loadOutDirsFromCheck = true,
--     buildScripts = { enable = true },
--   },
--   checkOnSave = true,
--   diagnostics = { enable = true },
--   procMacro = { enable = true },
--   files = {
--     exclude = {
--       '.direnv',
--       '.git',
--       '.jj',
--       '.github',
--       '.gitlab',
--       'bin',
--       'node_modules',
--       'target',
--       'venv',
--       '.venv',
--     },
--     watcher = 'client',
--   },
--   cmd = { 'rust-analyzer' },
--   filetypes = { 'rust' },
-- }
--
-- -- gopls
-- vim.lsp.config.gopls = {
--   cmd = { 'gopls' },
--   filetypes = { 'go', 'gomod', 'gowork', 'gotmpl' },
-- }
--
-- -- Workaround for gopls not supporting semanticTokensProvider.
-- -- Synthesise a semanticTokensProvider from the client's
-- -- capabilities so highlighting still works.
-- require('snacks').util.lsp.on({ name = 'gopls' }, function(_, client)
--   if client.config and client.config.init_options and client.config.init_options.semanticTokens and not client.server_capabilities.semanticTokensProvider then
--     local semantic = client.config.capabilities.textDocument.semanticTokens
--     client.server_capabilities.semanticTokensProvider = {
--       full = true,
--       legend = {
--         tokenTypes = semantic.tokenTypes,
--         tokenModifiers = semantic.tokenModifiers,
--       },
--       range = true,
--     }
--   end
-- end)
--
-- -- kotlin-language-server
-- vim.lsp.config.kotlin_language_server = { cmd = { 'kotlin-language-server' }, filetypes = { 'kotlin' } }
--
-- -- Servers registered by config.lang.* modules. Each carries its own cmd so
-- -- the launch command never depends on a plugin's mapping table. The mason
-- -- binary names are the source of truth (see stdpath("data")/mason/bin).
-- vim.lsp.config.lua_ls = { cmd = { 'lua-language-server' }, filetypes = { 'lua' } }
-- vim.lsp.config.clangd = {
--   cmd = {
--     'clangd',
--     '--background-index',
--     '--clang-tidy',
--     '--header-insertion=iwyu',
--     '--completion-style=detailed',
--     '--function-arg-placeholders',
--     '--fallback-style=llvm',
--   },
--   filetypes = { 'c', 'cpp', 'cxx', 'h', 'hpp', 'cc', 'c++', 'cuda', 'objc', 'cuda', 'objc' },
--   root_markers = {
--     'compile_commands.json',
--     'compile_flags.txt',
--     'configure.ac',
--     'Makefile',
--     'configure.in',
--     'config.h.in',
--     'meson.build',
--     'meson_options.txt',
--     'build.ninja',
--     '.git',
--   },
--   capabilities = {
--     offsetEncoding = { 'utf-16' },
--   },
--   init_options = {
--     usePlaceholders = true,
--     completeUnimported = true,
--     clangdFileStatus = true,
--   },
-- }
-- vim.lsp.config.neocmake = { cmd = { 'neocmakelsp', 'stdio' }, filetypes = { 'cmake' } }
-- vim.lsp.config.dockerls = { cmd = { 'docker-langserver', '--stdio' }, filetypes = { 'dockerfile' } }
-- vim.lsp.config.docker_compose_language_service = {
--   cmd = { 'docker-compose-langserver', '--stdio' },
--   filetypes = { 'yaml', 'yml' },
-- }
-- vim.lsp.config.jsonls = { cmd = { 'vscode-json-language-server', '--stdio' }, filetypes = { 'json', 'jsonc', 'json5' } }
-- vim.lsp.config.marksman = { cmd = { 'marksman' }, filetypes = { 'markdown' } }
-- vim.lsp.config.pyright = { cmd = { 'pyright' }, filetypes = { 'python' } }
-- vim.lsp.config.ruff = {
--   cmd = { 'ruff' },
--   filetypes = { 'python' },
--   cmd_env = { RUFF_TRACE = 'messages' },
--   init_options = {
--     settings = {
--       logLevel = 'error',
--     },
--   },
-- }
-- vim.lsp.config.sqls = { cmd = { 'sqls' }, filetypes = { 'sql' } }
-- vim.lsp.config.svelte = { cmd = { 'svelteserver' }, filetypes = { 'svelte' } }
-- vim.lsp.config.tailwindcss = {
--   cmd = { 'tailwindcss-language-server' },
--   filetypes = {
--     'html',
--     'svelte',
--     'astro',
--     'templ',
--     'blade',
--     'php',
--     'javascriptreact',
--     'typescriptreact',
--     'javascript',
--     'typescript',
--   },
--   settings = {
--     tailwindCSS = {
--       includeLanguages = {
--         elixir = 'html-eex',
--         eelixir = 'html-eex',
--         heex = 'html-eex',
--       },
--     },
--   },
-- }
-- vim.lsp.config.terraformls = { cmd = { 'terraform-ls', 'serve' }, filetypes = { 'terraform' } }
-- vim.lsp.config.taplo = { cmd = { 'taplo', 'lsp' }, filetypes = { 'toml' } }
-- vim.lsp.config.zls = { cmd = { 'zls' }, filetypes = { 'zig' } }
--
-- local M = {}
--
-- function M.setup()
--   -- Enable every server that has a config registered. vim.lsp.enable()
--   -- starts clients on FileType for enabled servers; the per-language
--   -- configs from config.lang.* are registered by the time this runs
--   -- (config.lang is required via config.plugins, which init.lua loads
--   -- before config.lsp).
--   --
--   -- angularls is intentionally excluded: its mason binary
--   -- (angular-language-server) is not installed in this environment, so
--   -- enabling it would produce a failed start on every .astro buffer.
--   vim.lsp.enable {
--     'lua_ls',
--     'rust_analyzer',
--     'gopls',
--     'ts_ls',
--     'kotlin_language_server',
--     'clangd',
--     'neocmake',
--     'dockerls',
--     'docker_compose_language_service',
--     'jsonls',
--     'marksman',
--     'pyright',
--     'ruff',
--     'sqls',
--     'svelte',
--     'tailwindcss',
--     'terraformls',
--     'taplo',
--     'zls',
--   }
-- end
--
-- return M
--
-- -- vim: ts=2 sts=2 sw=2 et
