local set = vim.opt

vim.g.lazygit_floating_window_winblend = 0

set.autoindent = true
set.autoread = true
set.autowrite = true
set.backspace = "indent,eol,start"
set.breakindent = true
set.clipboard = "unnamedplus"
set.cursorline = true
set.cursorlineopt = 'number'
set.expandtab = false
set.formatoptions:remove({ 'c', 'r', 'o' })
set.hidden = true
set.hlsearch = true
set.inccommand = "split"
set.incsearch = true
set.infercase = true
set.ignorecase = true
set.laststatus = 2
set.mouse = "a"
set.mousemoveevent = true
set.number = true
set.relativenumber = true
set.relativenumber = true
set.shiftround = true
set.shiftwidth = 2
set.showcmd = true
set.showmatch = true
set.smartcase = true
set.smartindent = true
set.softtabstop = 2
set.swapfile = false
set.tabstop = 2
set.undodir = vim.fn.stdpath("data") .. "/undo"
set.termguicolors = true
set.undofile = true
set.updatetime = 200
set.wrap = false
